### PR TITLE
Copyedit README.md for clarity & consistency

### PR DESCRIPTION
**Pull request by pkq**
This pull request includes a number of minor suggestions to improve clarity & consistency within README.md and adds links to rlang, dplyr, the programming with dplyr vignette, & RStudio addins. Hope you find it useful.

### CODE REVIEW

**Comment by MilesMcBain** [comment]
Thankyou so much for this!

Since you've read over it, I'd be interested in your opinion on moving out the functions/operators into an 'Overview' section above the 'Writing functions that call dplyr' section. Need to rework things a little.

**Comment by pkq** [comment]
You're welcome! I'd be happy to put some thought into how to best organize things. I should have some time in a few hours.

**Comment by pkq** [comment]
After trying it both ways, I think including an 'Overview' makes good sense. I just pushed another commit that makes those changes, along with rephrasing a few other things. Take a look and let me know what you think. I'm really excited about the potential of this package to help ease folks into the world of `tidyeval`!

**Comment by MilesMcBain** [comment]
I was just asking for an opinion! The fact you went and did it is awesome, and as I suspected it has worked out well. Thank you. I am stoked with how this is turning out.

**Comment by pkq** [comment]
As am I! Let me know if if you need another set of eyes on anything else.

**Comment by MilesMcBain** [comment]
There's a couple of little things that need to be fixed in this, but I'm so happy with it I'm going to merge it and use it as the basis.

Re other todos, there's harmonising all the documentation for the functions with our new explanation.

**Comment by pkq** [comment]
Fantastic! There's also the small issue of actually renaming the functions themselves, correct?

**Comment by MilesMcBain** [comment]
I think I have done the renames. It's getting the doco and tests up to scratch now.

**Pull request merged**
